# Generated by Django 5.2.5 on 2025-09-03 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('loser', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'id'], name='created_uuid_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='pokemon_name_idx')],
            },
        ),
    ]
