# Generated by Django 5.2.5 on 2025-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
